### ISSUE TITLE
Future of *-KeePassConfiguration?

### ISSUE THREAD

**Issue by ThomasSchoeller** [PSKeePass/PSKeePass#25]
What is the future of {Get,Set}-KeePassConfiguration? You are embedding the KeePass binary, leaves only the DB and Key File properties.

Will you remove these functions? I'm asking because replace it with something like https://github.com/PoshCode/Configuration. This would also make it possible to have per user settings, even the module is installed in the host module directory.

**Comment by jkdba** [comment]
Hi @ThomasSchoeller, this looks like a good idea and I see your point. One of the things I was looking at doing with the Configuration XML File that these functions manage is saving custom password profiles.

I have only glanced over the Configuration module and I am not fully aware of its capabilities when it comes to adding more "configurations" over time. From what I see it looks like it can but I would have to play with it. 

The other concern would be having another dependency to manage. Including what would be the best way to include this module, other than requiring the user to already to have it installed. If they have it installed and update it and this module is not ready for that update then it breaks. So we could require a specific version given that they version the module.

I am open to discussing this further, if you want to reach out via skype and walk through the details.

**Comment by ThomasSchoeller** [comment]
Hi @jkdba,
i didn't use the Configuration module, but it seams nice. Specially the feature of layered configurations.

Maybe dependency management can be done with #require module (https://technet.microsoft.com/en-us/library/hh847765.aspx)

In PSGallery there is also some dependency management.

**Comment by jkdba** [comment]
Sticking with xml on this for now, as it allows for more custom configuration.
