### ISSUE TITLE
Strictly Typed Parameters in Cmdlets

### ISSUE THREAD

**Issue by jkdba** [PSKeePass/PSKeePass#5]
I could add this to wiki for discussion, but currently the code I added from my project has "Strictly Typed" parameters meaning they are typed as something specific to the KeePass SDK.

Ex: (**[KeePassLib.PwDatabase]**)
```
    [CmdletBinding()]
    param
    (
        [Parameter(Position=0, Mandatory)]
        [ValidateNotNullOrEmpty()]
        [KeePassLib.PwDatabase] $Connection
    )
```

This means that the SDK must be loaded before the majority of cmdlets will function. I do not think this will be an issue going forward once issue #2 is complete however, in the meantime I solved this issue in my previous project by loading the DLL at the bottom of the module (_where you export the various cmdlets in the module_).

Alternatively I could remove the strong typing and set all of these parameters to a custom powershell object type, however this will reduce parameter validation and make the code more ambiguous. 

Thoughts?

**Comment by chritea** [comment]
Let's go with strict types. As you said we want to include the dlls so I see no Problem there

**Comment by jkdba** [comment]
Ok great!
